SET search_path TO 'nablarch';

CREATE TABLE IF NOT EXISTS CODE_NAME (
  CODE_ID CHAR(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  LANG CHAR(2) NOT NULL,
  SORT_ORDER SMALLINT NOT NULL,
  CODE_NAME VARCHAR(50) NOT NULL,
  SHORT_NAME VARCHAR(50),
  OPTION01 VARCHAR(50),
  OPTION02 VARCHAR(50),
  OPTION03 VARCHAR(50),
  OPTION04 VARCHAR(50),
  OPTION05 VARCHAR(50),
  OPTION06 VARCHAR(50),
  OPTION07 VARCHAR(50),
  OPTION08 VARCHAR(50),
  OPTION09 VARCHAR(50),
  OPTION10 VARCHAR(50),
  PRIMARY KEY (CODE_ID, CODE_VALUE, LANG)
);
CREATE TABLE IF NOT EXISTS CODE_PATTERN (
  CODE_ID CHAR(8) NOT NULL,
  CODE_VALUE VARCHAR(2) NOT NULL,
  PATTERN01 CHAR(1) NOT NULL,
  PATTERN02 CHAR(1),
  PATTERN03 CHAR(1),
  PATTERN04 CHAR(1),
  PATTERN05 CHAR(1),
  PATTERN06 CHAR(1),
  PATTERN07 CHAR(1),
  PATTERN08 CHAR(1),
  PATTERN09 CHAR(1),
  PATTERN10 CHAR(1),
  PATTERN11 CHAR(1),
  PATTERN12 CHAR(1),
  PATTERN13 CHAR(1),
  PATTERN14 CHAR(1),
  PATTERN15 CHAR(1),
  PATTERN16 CHAR(1),
  PATTERN17 CHAR(1),
  PATTERN18 CHAR(1),
  PATTERN19 CHAR(1),
  PATTERN20 CHAR(1),
  PRIMARY KEY (CODE_ID, CODE_VALUE)
);
CREATE TABLE IF NOT EXISTS USER_SESSION (
  SESSION_ID VARCHAR(100) NOT NULL,
  SESSION_OBJECT BYTEA NOT NULL,
  EXPIRATION_DATETIME TIMESTAMP NOT NULL,
  PRIMARY KEY (SESSION_ID)
);
ALTER TABLE CODE_NAME
ADD 
FOREIGN KEY (
  CODE_ID,
  CODE_VALUE
) REFERENCES CODE_PATTERN (
  CODE_ID,
  CODE_VALUE
);

DELETE FROM CODE_NAME;
DELETE FROM CODE_PATTERN;


INSERT INTO CODE_PATTERN(CODE_ID, CODE_VALUE, PATTERN01, PATTERN02, PATTERN03, PATTERN04, PATTERN05, PATTERN06, PATTERN07, PATTERN08, PATTERN09, PATTERN10, PATTERN11, PATTERN12, PATTERN13, PATTERN14, PATTERN15, PATTERN16, PATTERN17, PATTERN18, PATTERN19, PATTERN20) VALUES('C0000001', '0', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO CODE_PATTERN(CODE_ID, CODE_VALUE, PATTERN01, PATTERN02, PATTERN03, PATTERN04, PATTERN05, PATTERN06, PATTERN07, PATTERN08, PATTERN09, PATTERN10, PATTERN11, PATTERN12, PATTERN13, PATTERN14, PATTERN15, PATTERN16, PATTERN17, PATTERN18, PATTERN19, PATTERN20) VALUES('C0000001', '1', '1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '');

INSERT INTO CODE_NAME(CODE_ID, CODE_VALUE, LANG, SORT_ORDER, CODE_NAME, SHORT_NAME, OPTION01, OPTION02, OPTION03, OPTION04, OPTION05, OPTION06, OPTION07, OPTION08, OPTION09, OPTION10) VALUES('C0000001', '0', 'ja', '1', 'アンロック', 'アンロック', '-', '', '', '', '', '', '', '', '', '');
INSERT INTO CODE_NAME(CODE_ID, CODE_VALUE, LANG, SORT_ORDER, CODE_NAME, SHORT_NAME, OPTION01, OPTION02, OPTION03, OPTION04, OPTION05, OPTION06, OPTION07, OPTION08, OPTION09, OPTION10) VALUES('C0000001', '1', 'ja', '2', 'ロック', 'ロック', '-', '', '', '', '', '', '', '', '', '');


commit;