- name: Install tomcat
  become: true
  hosts: all
  tasks:
    - name: Install yum
      yum:
        name:
          - java-1.8.0-openjdk
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps

    - name: Start & Enable tomcat
      systemd:
        name: tomcat
        state: started
        enabled: true

    - name: Wait for listened port
      wait_for:
        port: 8080

    - name: Copy firewalld service xml
      copy:
        src: /vagrant/ap/resources/tomcat.xml
        dest: /usr/lib/firewalld/services/
        mode: 0644

    - name: Allow access tomcat
      firewalld:
        service: tomcat
        permanent: true
        state: enabled