- name: Install tomcat
  become: true
  hosts: all
  tasks:
    - name: Install yum
      yum:
        name:
          - java-1.8.0-openjdk
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps
          - wget

    - name: Download Postgres
      get_url:
        url: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
        dest: /tmp

    - name: Import Postgers
      yum:
        name: /tmp/pgdg-centos10-10-2.noarch.rpm
        state: present

    - name: Install yum
      yum:
        name:
          - postgresql10-libs
          - postgresql10
          - postgresql10-server

    - name: run initdb
      shell: /usr/pgsql-10/bin/postgresql-10-setup initdb
      args:
        creates: /var/lib/pgsql/10/data/*

    - name: change trust default auth for local
      replace:
        path: /var/lib/pgsql/10/data/pg_hba.conf
        regexp: '^(local +all +all +)peer'
        replace: '\1trust'

    - name: Start & Enable Postgres
      systemd:
        name: postgresql-10.service
        daemon-reload: true
        state: started
        enabled: true

    - name: Start & Enable tomcat
      systemd:
        name: tomcat
        daemon-reload: true
        state: started
        enabled: true

    - name: Wait for listened port
      wait_for:
        port: 8080

    - name: Copy firewalld service xml
      copy:
        src: /vagrant/ap/resources/tomcat.xml
        dest: /usr/lib/firewalld/services/
        mode: 0644

    - name: Allow access tomcat
      firewalld:
        service: tomcat
        permanent: true
        state: enabled