- name: Install PostgreSQL
  become: true
  hosts: all
  tasks:
    - name: Install yum
      yum:
        name:
          - wget

    - name: Download Postgres
      get_url:
        url: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
        dest: /tmp

    - name: Import Postgers
      yum:
        name: /tmp/pgdg-centos10-10-2.noarch.rpm
        state: present

    - name: Install yum
      yum:
        name:
          - postgresql10-libs
          - postgresql10
          - postgresql10-server
          - python-psycopg2

    - name: run initdb
      shell: /usr/pgsql-10/bin/postgresql-10-setup initdb
      args:
        creates: /var/lib/pgsql/10/data/*

    - name: change auth method for local
      replace:
        path: /var/lib/pgsql/10/data/pg_hba.conf
        regexp: '^(local +all +all +)peer'
        replace: '\1trust'

    - name: change auth method for IPv4 local
      replace:
        path: /var/lib/pgsql/10/data/pg_hba.conf
        regexp: '^(host +all +all +127\.0\.0\.1/32 +)ident'
        replace: '\1password'

    - name: Start & Enable Postgres
      systemd:
        name: postgresql-10.service
        daemon-reload: true
        state: started
        enabled: true

    - name: create a database
      postgresql_db:
        name: example
        login_user: postgres
        encoding: UTF-8
        template: template0

    - name: Create db user in postgre
      postgresql_user:
        name: nablarch
        db: example
        password: password123

    - name: Create scheme
      postgresql_schema:
        name: nablarch
        owner: nablarch
        database: example

    - name: drop public scheme
      postgresql_schema:
        name: public
        database: example
        state: absent

    - name: Create table
      shell: psql -f /vagrant/ap/resources/create.sql -U postgres -d example

    - name: Grant
      postgresql_privs:
        database: example
        type: table
        schema: nablarch
        roles: nablarch
        objs: ALL_IN_SCHEMA
        privs: SELECT,INSERT,UPDATE,DELETE
        grant_option: yes