- name: Install tomcat
  become: true
  hosts: all
  tasks:
    - name: Set locale
      shell: localectl set-locale LANG=ja_JP.UTF-8

    - name: Set timezone
      shell: timedatectl set-timezone Asia/Tokyo

    - name: Install yum
      yum:
        name:
          - java-1.8.0-openjdk
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps
          - wget
          - libsemanage-python

    - name: Regist clean target
      find:
        paths: /usr/share/tomcat/webapps
        file_type: any
        depth: 1
      register: somethins_to_delete

    - name: Clean example
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ somethins_to_delete.files }}"

    - name: Make app dir
      file:
        path: /var/nablarch/{{ item.name }}
        state: directory
        owner: tomcat
        group: tomcat
        mode: 0755
      with_items:
        - { name: 'output' }
        - { name: 'format' }

    - name: Download Postgres jdbc
      get_url:
        url: https://jdbc.postgresql.org/download/postgresql-42.2.5.jar
        dest: /usr/share/tomcat/lib/

    - name: Copy tomcat context xml for jndi
      copy:
        src: /vagrant/ap/resources/context.xml
        dest: /usr/share/tomcat/conf/
        owner: tomcat
        group: tomcat
        mode: 0644

    - name: Copy tomcat conf
      copy:
        src: /vagrant/ap/resources/lang.conf
        dest: /usr/share/tomcat/conf/conf.d/
        owner: tomcat
        group: tomcat
        mode: 0774

    - name: Set bool for tomcat connect db
      seboolean:
        name: tomcat_can_network_connect_db
        state: yes
        persistent: yes

    - name: Deploy war
      copy:
        src: /vagrant/ap/resources/exam-app.war
        dest: /usr/share/tomcat/webapps/
        mode: 0644

    - name: Start & Enable tomcat
      systemd:
        name: tomcat
        daemon-reload: true
        state: started
        enabled: true

    - name: Wait for listened port
      wait_for:
        port: 8080

    - name: Copy firewalld service xml
      copy:
        src: /vagrant/ap/resources/tomcat.xml
        dest: /usr/lib/firewalld/services/
        mode: 0644

    - name: Allow access tomcat
      firewalld:
        service: tomcat
        permanent: true
        state: enabled