- name: Install apache
  become: true
  hosts: all
  tasks:
    - name: Set locale
      shell: localectl set-locale LANG=ja_JP.UTF-8

    - name: Set timezone
      shell: timedatectl set-timezone Asia/Tokyo

    - name: Install apache
      yum:
        name:
          - httpd
          - libsemanage-python

    - name: Set bool for httpd_proxy
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Copy apache conf for ap
      copy:
        src: /vagrant/web/resources/ap_proxy.conf
        dest: /etc/httpd/conf.d/
        mode: 0644

    - name: Start & Enable apache
      systemd:
        name: httpd
        state: started
        enabled: true
