# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"

  # webサーバ
  config.vm.define :web do | web |
    web.vm.hostname = "web"
    web.vm.network :private_network, ip: "192.168.33.10", virtualbox__intnet: "intnet"

    # ポートフォワーディングの設定
    web.vm.network "forwarded_port", guest: 80, host: 30080

    # プロキシ設定
    if Vagrant.has_plugin?("vagrant-proxyconf") && ENV['http_proxy']
      puts '- Proxy Setting ----------------------------------'
      puts ENV['http_proxy']
      web.proxy.http     = ENV['http_proxy']
      web.proxy.https    = ENV['http_proxy']
      web.proxy.no_proxy = "localhost,127.0.0.1"
      puts '--------------------------------------------------'
    end
    
    # シェル書くのが辛いのでプロビジョンはansibleローカル
    web.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "web/web_server.yml"
    end

  end

  # apサーバ
  config.vm.define :ap do | ap |
    ap.vm.hostname = "ap"
    ap.vm.network :private_network, ip: "192.168.33.11", virtualbox__intnet: "intnet"

    # ポートフォワーディングの設定
    ap.vm.network "forwarded_port", guest: 8080, host: 38080

    # プロキシ設定
    if Vagrant.has_plugin?("vagrant-proxyconf") && ENV['http_proxy']
      puts '- Proxy Setting ----------------------------------'
      puts ENV['http_proxy']
      ap.proxy.http     = ENV['http_proxy']
      ap.proxy.https    = ENV['http_proxy']
      ap.proxy.no_proxy = "localhost,127.0.0.1"
      puts '--------------------------------------------------'
    end

    # シェル書くのが辛いのでプロビジョンはansibleローカル
    ap.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ap/ap_server.yml"
    end

  end

end
